// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'VeriMask';

  @override
  String get enrollmentTitleSimple => 'Set up verification';

  @override
  String get enrollmentSubtitleSimple =>
      'It only takes a moment. Your information never leaves this device.';

  @override
  String get enrollmentStep1Simple => 'Look at the camera';

  @override
  String get enrollmentStep2Simple => 'Stay still';

  @override
  String get enrollmentStep3Simple => 'Turn your head slightly';

  @override
  String get enrollmentStep4Simple => 'Almost done...';

  @override
  String get enrollmentStep5Simple => 'Saving your profile...';

  @override
  String get enrollmentStartButton => 'Start verification';

  @override
  String get enrollmentPrivacyText =>
      'Your information never leaves your phone';

  @override
  String get enrollmentFailed =>
      'We couldn\'t create your profile. Please try again.';

  @override
  String get reEnrollmentRequired =>
      'We need to verify your identity before continuing.';

  @override
  String reEnrollmentBlocked(int days) {
    return 'You can try again in $days days.';
  }

  @override
  String get reEnrollmentContactSupport => 'If you need help, contact support.';

  @override
  String get cameraTitle => 'Capture photo';

  @override
  String get cameraPermissionRequired =>
      'We need access to your camera to continue.';

  @override
  String get cameraPermissionSettings => 'Open settings';

  @override
  String get cameraPermissionDenied =>
      'Camera permission was denied. Please grant permission to use the camera.';

  @override
  String get cameraPermissionPermanentlyDenied =>
      'Camera permission was permanently denied. Please enable it in settings to continue.';

  @override
  String get cameraPermissionRestricted =>
      'Camera access is restricted on this device. This may be due to parental controls or device policies.';

  @override
  String get cameraNotAvailable => 'The camera is not available right now.';

  @override
  String get handNotDetected => 'Show your hand in the camera.';

  @override
  String get handGuideSimple => 'Place your hand here';

  @override
  String get livenessPrompt => 'Turn your head slightly to the right';

  @override
  String get validationFailed =>
      'We couldn\'t verify your identity. Please try again.';

  @override
  String get processingPhoto => 'Processing your photo...';

  @override
  String get processingError =>
      'Something went wrong processing the photo. Please try again.';

  @override
  String get captureError => 'We couldn\'t take the photo. Please try again.';

  @override
  String get genericError => 'Something went wrong. Please try again.';

  @override
  String get resultTitle => 'Your verified photo';

  @override
  String get resultAuthentic => 'Verified photo';

  @override
  String get resultAuthenticDesc =>
      'Generated by VeriMask, unaltered, less than 2 hours ago.';

  @override
  String get resultAuthenticTip =>
      'Tip: Meet in a public place and ask them to come to a visible spot like a reception area.';

  @override
  String get resultTampered => 'Invalid photo';

  @override
  String get resultTamperedDesc =>
      'This photo failed the integrity check. It may have been altered.';

  @override
  String get resultExpired => 'Expired photo';

  @override
  String get resultExpiredDesc =>
      'This photo is over 2 hours old. Request a recent one.';

  @override
  String get resultSharePrompt => 'Share your verified photo';

  @override
  String get shareWhatsApp => 'Share on WhatsApp';

  @override
  String get shareTelegram => 'Share on Telegram';

  @override
  String get shareGeneric => 'Share';

  @override
  String get verifyQrTitle => 'Verify photo';

  @override
  String get verifyQrInstructions =>
      'Take a screenshot of the VeriMask photo you received and select it here.';

  @override
  String get verifyQrNoCode => 'No valid QR code found.';

  @override
  String get verifyQrReadError =>
      'We couldn\'t read the QR code. Try with a different image.';

  @override
  String get verifyPhotoButton => 'Verify photo';

  @override
  String get planFreeLabel => 'Free Plan';

  @override
  String get planPremiumLabel => 'Premium Plan';

  @override
  String get planLimitReached =>
      'You\'ve used your 10 free photos this month. Get Premium for unlimited photos!';

  @override
  String planPhotosRemaining(int count) {
    return '$count photos remaining this month';
  }

  @override
  String get planUpgradeButton => 'Get Premium';

  @override
  String get planUnlimited => 'Unlimited photos';

  @override
  String ttlExpiresSoon(int minutes) {
    return 'This photo will be automatically deleted in $minutes minutes.';
  }

  @override
  String get ttlExpired => 'This photo has expired and was deleted.';

  @override
  String get onboardingWelcome => 'Welcome to VeriMask';

  @override
  String get onboardingDescription =>
      'Prove it\'s you without showing your full face.';

  @override
  String get onboardingStep1Title => 'Set up your profile';

  @override
  String get onboardingStep1Body =>
      'Take a few photos so the app can recognize you.';

  @override
  String get onboardingStep2Title => 'Capture your verified photo';

  @override
  String get onboardingStep2Body =>
      'Show your hand and look at the camera. The app protects your face automatically.';

  @override
  String get onboardingStep3Title => 'Share with confidence';

  @override
  String get onboardingStep3Body =>
      'Send your verified photo directly via WhatsApp or Telegram.';

  @override
  String get onboardingGetStarted => 'Get started';

  @override
  String get onboardingSkip => 'Skip';

  @override
  String get onboardingNext => 'Next';

  @override
  String get secureStorageError =>
      'We couldn\'t save your profile securely. Please restart the app.';

  @override
  String get keyPairError =>
      'We couldn\'t set up photo security. Please restart the app.';

  @override
  String get segmentationFallback =>
      'We couldn\'t process the photo background. A simple background will be used.';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get aboutTitle => 'About VeriMask';

  @override
  String get privacyNote =>
      'All information is processed on your device. Nothing leaves your phone.';

  @override
  String get buttonRetry => 'Try again';

  @override
  String get buttonCancel => 'Cancel';

  @override
  String get buttonContinue => 'Continue';

  @override
  String get buttonDone => 'Done';

  @override
  String get progressDetectingHand => 'Detecting hand...';

  @override
  String get progressVerifyingIdentity =>
      'Turn your head slightly to the right...';

  @override
  String get progressProcessingPhoto => 'Processing photo...';

  @override
  String get progressCertifying => 'Certifying...';

  @override
  String get captureButtonSimple => 'Take anonymous VeriMask photo';

  @override
  String get takeAnotherPhoto => 'Take another photo';

  @override
  String get privacyBadge => '100% on your device';
}
